import Head from "next/head";
import styles from "../styles/Home.module.css";
import swal from "sweetalert2";
import AuthService from "./api/services/auth.service";
import { useRouter } from "next/router";
import { useState } from "react";

export default function Home() {
  const [username, setusername] = useState("");
  const [password, setPassword] = useState("");
  const router = useRouter();
  const handleLogin = async (e) => {
    e.preventDefault();
    if (username == "" || password == "") {
      new swal({
        title: "Digite sus credenciales!",
        text: "por favor digite sus credenciales para logearse!",
        icon: "warning",
        timer: "2000",
      });
    } else {
      try {
        await AuthService.login(username, password).then(
          () => {
            new swal({
              title: "Bienvenido!",
              text: "te logeaste exitosamente!",
              icon: "success",
              timer: "1200",
            });
            const timer = setTimeout(() => {
              router.push("/inicio");
            }, 100);
            return () => clearTimeout(timer);
          },
          (error) => {
            new swal({
              title: "credenciales incorrectas!",
              text: "por favor comprueba tus datos e intenta nuevamente!",
              icon: "error",
              timer: "2000",
            });
          }
        );
      } catch (err) {
        swal.fire({
          title: "error..!",
          text: "error de servidor",
          icon: "error",
          timer: "2000",
        });
      }
    }
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Konecta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.cont_login}>
          <div className={styles.cont_login_iz}>
            <div className={styles.cont_login_back}></div>
          </div>
          <div className={styles.cont_login_der}>
            <div className={styles.tittlee}>
              <label className={styles.label_title}>Konecta</label>
              <br></br>
              <br></br>
              <label className={styles.label_titler}>Welcome to Konecta</label>
            </div>
            <br></br>
            <label className={styles.label_login}>UserName</label>
            <input
              type="text"
              value={username}
              onChange={(e) => setusername(e.target.value)}
              className={styles.inputsl}
            ></input>
            <br></br>
            <label className={styles.label_login}>Psassword</label>
            <input
              type="text"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              className={styles.inputsl}
            ></input>
            <div className={styles.contebutton}>
              <button onClick={handleLogin} className={styles.buton}>
                Sing In
              </button>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
