import Navbar from "./Navbar";
import Head from "next/head";
import styles from "../styles/inicio.module.css";
import Login from "../pages/index.js";
import AuthService from "../pages/api/services/auth.service";
import { useState } from "react";
const Layout = ({ children }) => {
  const [valitoken, setvalitoken] = useState(1);
  async function obetener() {
    var tokenn = await AuthService.getCurrentUser();
    if (tokenn === null || tokenn === "") {
      setvalitoken(3);
    } else {
      setvalitoken(2);
    }
  }
  obetener();
  if (valitoken === 1) {
    return (
      <div className="loading">
        {" "}
        Loading&#8230;
      </div>
    );
  } else if (valitoken === 2) {
    return (
      <div className={styles.containerInicio}>
        <Head>
          <title>Konecta</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar />
        {children}
      </div>
    );
  } else {
    if (valitoken === 3) {
      return <Login />;
    }
  }
};
export default Layout;
